### ISSUE TITLE
Switch from system path to relative path

### ISSUE THREAD

**Issue by ProfDoof** [neovim/tree-sitter-vim#12]
As of https://github.com/tree-sitter/tree-sitter/pull/2573, the tree-sitter-cli `make install` no longer installs the `parser.h` file to the system. Now, we need to use the relative path instead otherwise it will fail to compile in the fuzzing action. However, the npm install and cargo install both still install the `parser.h` so if the fuzzing action can use npm or cargo to install the tree-sitter that would continue to work but it feels like a temporary bandage solution.

https://github.com/neovim/tree-sitter-vim/blob/77e9e96c2ae5cff7343ce3dced263483acf95793/src/scanner.c#L3

**Comment by clason** [comment]
I'm sorry, I have a hard time understanding what you are requesting here.

**Comment by ProfDoof** [comment]
This
[tree-sitter-vim/src/scanner.c](https://github.com/neovim/tree-sitter-vim/blob/77e9e96c2ae5cff7343ce3dced263483acf95793/src/scanner.c#L3)

needs to be changed to 
```c
#include "tree_sitter/parser.h"
``` 

in order to remain able to compile the scanner in the fuzzing action. Without this, since the fuzzing action uses `make install` and the `make install` no longer installs the `parser.h` to the system, you can't use the `<thing>` and must use `"thing"` instead to compile against the `parser.h` file that is in the repository.

**Comment by clason** [comment]
I don't understand; this file is autogenerated, and our actions work just fine. Why are you opening this issue for this parser in particular?
